### PR TITLE
Update app.js

### PR DESCRIPTION
**Pull request by dfarr**

### CODE REVIEW

**Comment by review-ninja** [comment]
[ReviewNinja](http://app.review.ninja/reviewninja/foo/pull/236)

**Comment by review-ninja** [comment]
<a href="http://review-ninja-staging.cfapps.io/reviewninja/foo/pull/236" target="_blank">ReviewNinja

**Comment by fabianschwarzfritz** [comment]
asdfasdfasdf

**Comment by fabianschwarzfritz** [comment]
asdfasdfasdfasdfasdfasdfasdf

**Comment by fabianschwarzfritz** [comment]
asdfasdfasdfasdfasdfasdfasdfasdfsadf

**Pull request closed without merging**
